version: "3.9"
services:

  app:
#    folder with app source in relation to docker-compose location
    build: .
    container_name: quizit-app-container
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL-jdbc:postgresql://db:5432/postgres}

  db:
    image: postgres:15.2
    container_name: quizit-db-container
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB-postgres}
      - POSTGRES_USER=${POSTGRES_USER-root}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD-pass}

volumes:
  postgres-data: